version: "3.8"

services:
  backend:
    build:
      context: ./backend/
    container_name: properties-backend-service
    environment:
      DATABASE_URL: $PROP_DB_URL
      BACKEND_PORT: $BACKEND_PORT
    restart: always
    ports:
      - 9000:9000

  properties_db:
    image: mysql:8.0
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: $PROP_DB_ROOT_PASS
      MYSQL_DATABASE: $PROP_DB_DB
      MYSQL_USER: $PROP_DB_USER
      MYSQL_PASSWORD: $PROP_DB_USER_PASS
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./backend/db/sql:/docker-entrypoint-initdb.d:ro
    ports:
      - 3307:3306

  frontend:
    build:
      context: ./frontend/
      # args:
      #   - REACT_APP_API_URL_BACKEND=$REACT_APP_API_URL_BACKEND
    container_name: properties-frontend-service
    restart: always
    ports:
      - 3001:80
